#!/bin/zsh -f
# Use BBEdit.app as your $EDITOR. This presumes that BBEdit.app and its
# command line tool are both already installed
#
# From:	Timothy J. Luoma
# Mail:	luomat at gmail dot com
# Date:	2013-05-13

NAME="$0:t:r"

if ((! $+commands[bbedit] ))
then

	# note: if bbedit is a function or alias, it will come back not found

	echo "$NAME: 'bbedit' is required but not found in $PATH"
	exit 1

fi


if [ "$SSH" = "yes" ]
then

	# we are logged in via SSH according to $SSH so we need to use a
	# command line text editor. Add in your preferences here. The first one
	# which is found will be used.

	echo -n "$NAME: you are logged in via SSH (\$SSH = $SSH). Looking for alternate editor: "

	if [ -x /usr/bin/nano ]
	then
			echo "found 'nano'"

			/usr/bin/nano -w -- "$@"

	elif [ -x /usr/bin/pico ]
	then
			echo "found 'pico'"
			/usr/bin/pico -w -- "$@"

	else
			echo "could not find any alternative, so using 'vi'"
			sleep 2
			vi -- "$@"

	fi

else

	bbedit 	--language 'Unix Shell Script' \
			--create-unix \
			--new-window \
			--resume \
			--wait \
			-- "$@"

	EXIT="$?"

	if [ "$EXIT" = "0" ]
	then
			echo "	$NAME: 'bbedit' exited successfully."
			exit 0

	else
			echo "	$NAME: 'bbedit' exited uncleanly (\$EXIT = $EXIT)"

			exit 1
	fi

fi

#
#EOF
